openapi: "3.0.0"
info:
  title: OpenAPI Demo
  version: 3.0.0
paths:
  /students:
    get:
      summary: List all students
      operationId: listStudents
      tags:
        - students
      responses:
        '200':
          description: Successfully List all students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './students.model.yml/#/components/schemas/Student'
    post:
      summary: Create a student
      operationId: createStudents
      tags:
        - students
      requestBody:
        content:
          application/json:
            schema:
              $ref: './students.model.yml/#/components/schemas/StudentCreateObject'
      responses:
        '200':
          description: Successfully Created a student
          content:
            application/json:
              example: '{"message": "Student created successfully!"}'
    put:
      summary: Modify a student
      operationId: modifyStudents
      tags:
        - students
      requestBody:
        content:
          application/json:
            schema:
              $ref: './students.model.yml/#/components/schemas/Student'
      responses:
        '200':
          description: Successfully Modified a student
          content:
            application/json:
              example: '{"message": "Student modified successfully!"}'
  /students/{studentId}:
    get:
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
      summary: Info for a specific student
      operationId: showStudentsById
      tags:
        - students
      responses:
        '200':
          description: Successful Info for a specific student
          content:
            application/json:
              schema:
                $ref: './students.model.yml/#/components/schemas/Student'
    delete:
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
      summary: Delete specific student
      operationId: deleteStudentsById
      tags:
        - students
      responses:
        '200':
          description: Successfully Deleted a student
          content:
            application/json:
              example: '{"message": "Student deleted successfully!"}'
